version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - export BUCKET=hw3-static-website
#       - aws s3 cp LF0.zip s3://voicecontrolledsearchb2/LF0.zip
      - aws cloudformation package --template-file lambda_function_serverless.yaml --s3-bucket $BUCKET --output-template-file lambda_function_serverless.yaml
artifacts:
  type: zip
  files:
    - lambda_function_serverless.yaml